language: python

services:
  - docker

before_install:
  - docker build deep-learning-from-scratch:1.0.0 -f docker/Dockerfile .

script:
  - docker run --rm -v ${TRAVIS_BUILD_DIR}:/build -w /build deep-learning-from-scratch:1.0.0 bash -ex run_ci.sh
